<?php

namespace app\home\controller;

use app\common\model\Category;
use think\Controller;

/**
 *  订单管理
 * Class Flow
 * @package app\home\controller
 */

// 判断是否登陆，如果没有登陆，登陆后在操作
// 地址信息 如果有就用个人中心的
// 如果没有就添加

class Flow extends Controller
{
    private $categoryData;

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub

        // 调取分类数据
        // 获取后台分类表数据
        $this->categoryData = (new Category())->where('pid',0)->select();
    }
    /**
     *  结算页面
     */
    public function index(){

        $categoryData = $this->categoryData;
        return view('',compact('categoryData'));
    }
}
