<?php

namespace app\home\controller;

use app\common\model\Category;
use think\Controller;
use app\common\model\User;
use think\Session;

/**
 *  订单管理
 * Class Flow
 * @package app\home\controller
 */

// 判断是否登陆，如果没有登陆，登陆后在操作
// 地址信息 如果有就用个人中心的
// 如果没有就添加

class Flow extends Controller
{
    private $categoryData;

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub

        // 调取分类数据
        // 获取后台分类表数据
        $this->categoryData = (new Category())->where('pid',0)->select();
    }
    /**
     *  结算页面
     */
    public function index(){

        // 获取地址栏数据
        // 获取地址栏信息
        $model = User::get(Session::get('user.user_id'));

        $address = $model->assAddr()->select();
        if($address){
            foreach ($address as $k =>$v){
                $v = $v->toArray();
                $v['address'] = json_decode($v['address'],true);
                $address[$k] = $v;

            }
        }
        $categoryData = $this->categoryData;
        return view('',compact('categoryData','address'));
    }
}
